name: somatic_n-of-1
channels:
  - r
  - pcgr
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - ascat
  - bam-readcount
  - bbmap
  - bcftools=1.9
  - bedtools
  - bioconductor-biomart
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-complexheatmap
  - bioconductor-customprodb
  - bioconductor-ensdb.hsapiens.v75
  - bioconductor-ensdb.hsapiens.v86
  - bioconductor-ensembldb
  - bioconductor-ensemblvep
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-org.hs.eg.db
  - bioconductor-purecn
  - bioconductor-rtracklayer
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bwa=0.7.17
  - cpsr=0.5.2.6
  - crcmod
  - ensembl-vep=98.3
  - fastp
  - fastqc
  - gatk4=4.1.3.0
  - htslib=1.9
  - libiconv
  - msisensor
  - multiqc
  - nextflow=19.10
  - octopus
  - pandoc
  - pcgr
  - perl=5.26
  - picard
  - pisces
  - r-circlize
  - r-data.table
  - r-devtools
  - r-facets=0.5.14
  - r-plyr
  - r-dplyr
  - r-pheatmap
  - r-stringi
  - r-tidyverse
  - samtools=1.9
  - snp-pileup
  - ucsc-liftover
  - varlociraptor
  - varscan
